name: 2FA-Paper
version: ${project.version}
main: me.physicsarebad.twofapaper.TwoFAPaper
authors: [PhysicsAreBad]
api-version: 1.13
description: Slave plugin for Two Factor Authentication that prevents movement on servers
